type Locale = 'es' | 'en' | 'ru';

const translations: Record<Exclude<Locale, 'es'>, Record<string, string>> = {
  en: {
    'La Guillotina': 'The Guillotine',
    'Revista anarquista': 'Anarchist magazine', 'Contra toda autoridad': 'Against all authority',
    'REVISTA ANARQUISTA / CONTRA TODA AUTORIDAD': 'ANARCHIST MAGAZINE / AGAINST ALL AUTHORITY',
    'Inicio': 'Home', 'Ediciones': 'Editions', 'Quiénes somos': 'About us', 'Manifiesto': 'Manifesto', 'Colaborar': 'Contribute', 'Contacto': 'Contact',
    'HECHA SIN AMO · SIN COPYRIGHT · COPIÁ · DIFUNDÍ · ORGANIZATE': 'MADE WITH NO MASTERS · NO COPYRIGHT · COPY · SHARE · ORGANIZE',
    'SEGUÍ LA SEÑAL': 'FOLLOW THE SIGNAL', 'Playlist en Spotify': 'Spotify playlist', 'Canal de YouTube': 'YouTube channel',
    'INGRESAR / SUMATE': 'SIGN IN / JOIN', 'ACCESO / COMUNIDAD': 'ACCESS / COMMUNITY',
    'EL ARCHIVO SE CONSTRUYE ENTRE MUCHAS': 'THE ARCHIVE IS BUILT BY MANY',
    'No entregamos tus datos. La información circula con cuidado y las métricas son anónimas por defecto.': 'We do not give away your data. Information circulates with care and analytics are anonymous by default.',
    'Tu sesión y tus preferencias se gestionan de forma segura para que puedas conservar lecturas, comentarios y guardadas.': 'Your session and preferences are managed securely so you can keep readings, comments, and saved notes.',
    'VOLVÉ A ENTRAR': 'COME BACK IN', 'Ingresá para seguir conversaciones, guardar lecturas y participar.': 'Sign in to follow conversations, save readings, and participate.', 'INGRESAR': 'SIGN IN',
    'SUMATE A LA RED': 'JOIN THE NETWORK', 'Creá tu acceso para dejar notas, seguir publicaciones y sostener este archivo común.': 'Create access to leave notes, follow publications, and support this shared archive.', 'CREAR CUENTA': 'CREATE ACCOUNT',
    'MEMORIA EN PAPEL': 'MEMORY ON PAPER', 'Archivo de': 'Archive of', 'ediciones': 'editions',
    'Una colección en construcción. Cada número es una conversación que no termina.': 'A collection under construction. Every issue is a conversation that does not end.',
    'Revistas': 'Magazines', 'Libros': 'Books', 'Muestra': 'Showcase', 'Multimedia': 'Multimedia',
    'Todavía no hay libros publicados. Próximamente encontrarás cuadernos, investigaciones y textos para descargar.': 'There are no published books yet. Soon you will find notebooks, research, and downloadable texts.',
    'QUIÉNES SOMOS': 'ABOUT US', 'Una red de': 'A network of', 'voces indóciles.': 'untamed voices.',
    'La Guillotina nace de la necesidad de encontrarnos fuera de las instituciones que administran nuestras vidas.': 'La Guillotina was born from the need to meet beyond the institutions that administer our lives.',
    'Somos un colectivo abierto de personas que escriben, dibujan, investigan, traducen, fotografían y hacen cosas con sus manos. No hablamos por nadie: hacemos sitio para que hablen muchas.': 'We are an open collective of people who write, draw, research, translate, photograph, and make things with their hands. We do not speak for anyone: we make room for many voices.',
    'Creemos en la autonomía, el apoyo mutuo, la imaginación y la alegría como prácticas políticas.': 'We believe in autonomy, mutual aid, imagination, and joy as political practices.',
    'MANIFIESTO': 'MANIFESTO', 'No hay libertad': 'There is no freedom', 'sin desobediencia.': 'without disobedience.',
    'No pedimos permiso para existir, pensar ni organizarnos.': 'We do not ask permission to exist, think, or organize.',
    'Desconfiamos de todo poder que se pretenda necesario.': 'We distrust every power that calls itself necessary.',
    'Practicamos el apoyo mutuo antes que la competencia.': 'We practice mutual aid before competition.',
    'Defendemos una cultura libre, situada y compartida.': 'We defend a free, situated, shared culture.',
    'Hacemos de la crítica una herramienta y del cuidado, una fuerza.': 'We make critique a tool and care a force.',
    'La libertad se practica': 'Freedom is a practice',
    'No esperamos autorización para pensar, crear o reunirnos. La autonomía empieza cuando reconocemos nuestra capacidad colectiva para decidir.': 'We do not wait for authorization to think, create, or gather. Autonomy begins when we recognize our collective capacity to decide.',
    'Desobedecer no es un gesto vacío: es abrir espacio para otras relaciones, asumir sus consecuencias y sostenerlas en común.': 'Disobedience is not an empty gesture: it opens space for other relationships, accepts their consequences, and sustains them together.',
    'Ningún poder es inevitable': 'No power is inevitable',
    'Toda autoridad que se presenta como natural oculta una historia, intereses y mecanismos concretos de obediencia.': 'Every authority presented as natural conceals a history, interests, and concrete mechanisms of obedience.',
    'Interrogar esas estructuras permite imaginar cómo desmontarlas sin reemplazar un mando por otro.': 'Questioning those structures lets us imagine how to dismantle them without replacing one command with another.',
    'El apoyo mutuo organiza': 'Mutual aid organizes',
    'Cooperar no es caridad ni una solución de emergencia: es una manera material de distribuir recursos, tiempo y conocimiento.': 'Cooperation is neither charity nor an emergency fix: it is a material way to distribute resources, time, and knowledge.',
    'Las redes que construimos hoy ensayan formas de vida donde nadie queda aislado frente a una necesidad.': 'The networks we build today rehearse forms of life where no one is left alone in the face of need.',
    'La cultura debe circular': 'Culture must circulate',
    'Las ideas crecen cuando pueden copiarse, traducirse, discutirse y transformarse en contextos que sus autoras no controlan.': 'Ideas grow when they can be copied, translated, discussed, and transformed in contexts their authors do not control.',
    'Defendemos una cultura situada que reconoce procedencias y cuidados sin convertir el conocimiento en propiedad cercada.': 'We defend a situated culture that acknowledges origins and care without turning knowledge into fenced property.',
    'Cuidar también es luchar': 'Care is also struggle',
    'La crítica pierde fuerza si reproduce el agotamiento, el desprecio o las jerarquías que pretende cuestionar.': 'Critique loses strength when it reproduces exhaustion, contempt, or the hierarchies it claims to challenge.',
    'Hacer lugar para la escucha, el descanso y la alegría vuelve sostenible la rebeldía y amplía quiénes pueden participar.': 'Making room for listening, rest, and joy makes rebellion sustainable and broadens who can take part.',
    'COLABORAR': 'CONTRIBUTE', 'Mandá una chispa.': 'Send a spark.', 'Hagamos incendio.': 'Let us make a fire.',
    'Buscamos textos, ilustraciones, fotos, poemas, crónicas, traducciones y afiches.': 'We are looking for texts, illustrations, photos, poems, chronicles, translations, and posters.',
    'No hace falta tener currículum ni hablar como un libro. Nos interesan las ideas que nacen de la experiencia y las preguntas que vale la pena sostener.': 'You do not need a résumé or bookish language. We care about ideas born from experience and questions worth sustaining.',
    'Escribir a la redacción': 'Write to the editorial collective', 'APOYO MUTUO': 'MUTUAL AID', 'Sostené el archivo.': 'Support the archive.', 'DONAR POR MERCADO PAGO': 'DONATE WITH MERCADO PAGO',
    'CONTACTO': 'CONTACT', 'Dejá una nota': 'Leave a note', 'en la puerta.': 'at the door.',
    'Para preguntas, alianzas y mensajes que necesiten llegar a algún lado.': 'For questions, alliances, and messages that need to go somewhere.',
    'Nombre': 'Name', '¿Cómo te llamás?': 'What is your name?', 'Correo': 'Email', 'Mensaje': 'Message', 'Escribí sin pedir perdón.': 'Write without apologizing.', 'Enviar mensaje →': 'Send message →',
    'GUÍA DE LECTURA': 'READING GUIDE', 'Herramientas para': 'Tools to', 'recorrer el archivo.': 'explore the archive.', 'Atajos y opciones disponibles para leer sin apuro.': 'Shortcuts and options for unhurried reading.',
    'Abrí la búsqueda global.': 'Open global search.', 'Cambiá de nota cuando una está abierta.': 'Move between notes while one is open.', 'Cerrá búsquedas, notas e imágenes ampliadas.': 'Close searches, notes, and enlarged images.', 'Acercá o alej á las imágenes ampliadas.': 'Zoom enlarged images in or out.',
    'Elegí idioma, color, tamaño de texto, tipografía y contraste. Tus elecciones se guardan en este navegador.': 'Choose language, color, text size, typography, and contrast. Your choices are saved in this browser.',
    'ARCHIVO EN PREPARACIÓN': 'ARCHIVE IN PREPARATION', 'Lo que viene': 'What is coming', 'también circula.': 'also circulates.',
    'Estamos preparando nuevas ediciones, lecturas, muestras y registros para sumar al archivo común.': 'We are preparing new issues, readings, showcases, and records for the shared archive.',
    'Mientras tanto, podés recorrer las publicaciones actuales, guardar notas y volver cuando la tinta se mueva otra vez.': 'Meanwhile, explore current publications, save notes, and return when the ink moves again.', 'IR AL ARCHIVO →': 'GO TO ARCHIVE →',
    'ERROR 404': 'ERROR 404', 'Esta página': 'This page', 'se fugó.': 'escaped.', 'La imprenta sigue encendida, pero esta hoja no está en el archivo.': 'The press is still running, but this sheet is not in the archive.', 'Volver a la portada': 'Back to the cover',
    'Gato negro junto a una imprenta abandonada': 'Black cat beside an abandoned printing press',
  },
  ru: {
    'La Guillotina': 'Гильотина',
    'Revista anarquista': 'Анархистский журнал', 'Contra toda autoridad': 'Против всякой власти',
    'REVISTA ANARQUISTA / CONTRA TODA AUTORIDAD': 'АНАРХИСТСКИЙ ЖУРНАЛ / ПРОТИВ ВСЯКОЙ ВЛАСТИ',
    'Inicio': 'Главная', 'Ediciones': 'Издания', 'Quiénes somos': 'О нас', 'Manifiesto': 'Манифест', 'Colaborar': 'Участвовать', 'Contacto': 'Контакт',
    'HECHA SIN AMO · SIN COPYRIGHT · COPIÁ · DIFUNDÍ · ORGANIZATE': 'СОЗДАНО БЕЗ ХОЗЯЕВ · БЕЗ COPYRIGHT · КОПИРУЙ · ДЕЛИСЬ · ОРГАНИЗУЙСЯ',
    'SEGUÍ LA SEÑAL': 'СЛЕДУЙ ЗА СИГНАЛОМ', 'Playlist en Spotify': 'Плейлист Spotify', 'Canal de YouTube': 'Канал YouTube',
    'INGRESAR / SUMATE': 'ВОЙТИ / ПРИСОЕДИНИТЬСЯ', 'ACCESO / COMUNIDAD': 'ДОСТУП / СООБЩЕСТВО', 'EL ARCHIVO SE CONSTRUYE ENTRE MUCHAS': 'АРХИВ СОЗДАЮТ МНОГИЕ',
    'No entregamos tus datos. La información circula con cuidado y las métricas son anónimas por defecto.': 'Мы не передаём ваши данные. Информация обращается бережно, а аналитика по умолчанию анонимна.',
    'Tu sesión y tus preferencias se gestionan de forma segura para que puedas conservar lecturas, comentarios y guardadas.': 'Сессия и настройки защищены, чтобы сохранять чтения, комментарии и заметки.',
    'VOLVÉ A ENTRAR': 'ВОЙТИ СНОВА', 'Ingresá para seguir conversaciones, guardar lecturas y participar.': 'Войдите, чтобы следить за обсуждениями, сохранять чтения и участвовать.', 'INGRESAR': 'ВОЙТИ',
    'SUMATE A LA RED': 'ПРИСОЕДИНИТЬСЯ К СЕТИ', 'Creá tu acceso para dejar notas, seguir publicaciones y sostener este archivo común.': 'Создайте доступ, чтобы оставлять заметки, следить за публикациями и поддерживать общий архив.', 'CREAR CUENTA': 'СОЗДАТЬ АККАУНТ',
    'MEMORIA EN PAPEL': 'ПАМЯТЬ НА БУМАГЕ', 'Archivo de': 'Архив', 'ediciones': 'изданий',
    'Una colección en construcción. Cada número es una conversación que no termina.': 'Коллекция в процессе создания. Каждый номер — разговор, который не заканчивается.',
    'Revistas': 'Журналы', 'Libros': 'Книги', 'Muestra': 'Выставка', 'Multimedia': 'Мультимедиа',
    'Todavía no hay libros publicados. Próximamente encontrarás cuadernos, investigaciones y textos para descargar.': 'Опубликованных книг пока нет. Скоро появятся тетради, исследования и тексты для скачивания.',
    'QUIÉNES SOMOS': 'О НАС', 'Una red de': 'Сеть', 'voces indóciles.': 'непокорных голосов.',
    'La Guillotina nace de la necesidad de encontrarnos fuera de las instituciones que administran nuestras vidas.': 'La Guillotina родилась из потребности встречаться вне институтов, управляющих нашими жизнями.',
    'Somos un colectivo abierto de personas que escriben, dibujan, investigan, traducen, fotografían y hacen cosas con sus manos. No hablamos por nadie: hacemos sitio para que hablen muchas.': 'Мы — открытый коллектив людей, которые пишут, рисуют, исследуют, переводят, фотографируют и создают вещи своими руками. Мы не говорим ни за кого: мы даём место многим голосам.',
    'Creemos en la autonomía, el apoyo mutuo, la imaginación y la alegría como prácticas políticas.': 'Мы верим в автономию, взаимопомощь, воображение и радость как в политические практики.',
    'MANIFIESTO': 'МАНИФЕСТ', 'No hay libertad': 'Нет свободы', 'sin desobediencia.': 'без неповиновения.',
    'No pedimos permiso para existir, pensar ni organizarnos.': 'Мы не просим разрешения существовать, думать и организовываться.',
    'Desconfiamos de todo poder que se pretenda necesario.': 'Мы не доверяем любой власти, считающей себя необходимой.', 'Practicamos el apoyo mutuo antes que la competencia.': 'Мы выбираем взаимопомощь вместо конкуренции.',
    'Defendemos una cultura libre, situada y compartida.': 'Мы защищаем свободную, локальную и общую культуру.', 'Hacemos de la crítica una herramienta y del cuidado, una fuerza.': 'Мы делаем критику инструментом, а заботу — силой.',
    'La libertad se practica': 'Свобода — это практика',
    'No esperamos autorización para pensar, crear o reunirnos. La autonomía empieza cuando reconocemos nuestra capacidad colectiva para decidir.': 'Мы не ждём разрешения думать, создавать или собираться. Автономия начинается с признания нашей общей способности принимать решения.',
    'Desobedecer no es un gesto vacío: es abrir espacio para otras relaciones, asumir sus consecuencias y sostenerlas en común.': 'Неповиновение — не пустой жест: оно открывает пространство для иных отношений, принимает последствия и поддерживает их сообща.',
    'Ningún poder es inevitable': 'Никакая власть не неизбежна',
    'Toda autoridad que se presenta como natural oculta una historia, intereses y mecanismos concretos de obediencia.': 'Любая власть, выдающая себя за естественную, скрывает историю, интересы и конкретные механизмы подчинения.',
    'Interrogar esas estructuras permite imaginar cómo desmontarlas sin reemplazar un mando por otro.': 'Критика этих структур помогает представить, как разобрать их, не заменяя одно управление другим.',
    'El apoyo mutuo organiza': 'Взаимопомощь организует',
    'Cooperar no es caridad ni una solución de emergencia: es una manera material de distribuir recursos, tiempo y conocimiento.': 'Сотрудничество — не благотворительность и не временная мера, а материальный способ распределять ресурсы, время и знания.',
    'Las redes que construimos hoy ensayan formas de vida donde nadie queda aislado frente a una necesidad.': 'Сети, которые мы строим сегодня, создают формы жизни, где никто не остаётся один перед необходимостью.',
    'La cultura debe circular': 'Культура должна циркулировать',
    'Las ideas crecen cuando pueden copiarse, traducirse, discutirse y transformarse en contextos que sus autoras no controlan.': 'Идеи растут, когда их можно копировать, переводить, обсуждать и менять в контекстах, которые авторы не контролируют.',
    'Defendemos una cultura situada que reconoce procedencias y cuidados sin convertir el conocimiento en propiedad cercada.': 'Мы защищаем укоренённую культуру, признающую происхождение и заботу, но не превращающую знание в огороженную собственность.',
    'Cuidar también es luchar': 'Забота — тоже борьба',
    'La crítica pierde fuerza si reproduce el agotamiento, el desprecio o las jerarquías que pretende cuestionar.': 'Критика теряет силу, если воспроизводит истощение, презрение или иерархии, которые стремится оспорить.',
    'Hacer lugar para la escucha, el descanso y la alegría vuelve sostenible la rebeldía y amplía quiénes pueden participar.': 'Пространство для слушания, отдыха и радости делает сопротивление устойчивым и расширяет круг участников.',
    'COLABORAR': 'УЧАСТВОВАТЬ', 'Mandá una chispa.': 'Пришли искру.', 'Hagamos incendio.': 'Разожжём огонь.',
    'Buscamos textos, ilustraciones, fotos, poemas, crónicas, traducciones y afiches.': 'Мы ищем тексты, иллюстрации, фотографии, стихи, хроники, переводы и плакаты.',
    'No hace falta tener currículum ni hablar como un libro. Nos interesan las ideas que nacen de la experiencia y las preguntas que vale la pena sostener.': 'Не нужны ни резюме, ни книжный язык. Нам интересны идеи, рожденные опытом, и вопросы, которые стоит поддерживать.',
    'Escribir a la redacción': 'Написать редакции', 'APOYO MUTUO': 'ВЗАИМОПОМОЩЬ', 'Sostené el archivo.': 'Поддержите архив.', 'DONAR POR MERCADO PAGO': 'ПОДДЕРЖАТЬ ЧЕРЕЗ MERCADO PAGO',
    'CONTACTO': 'КОНТАКТ', 'Dejá una nota': 'Оставь записку', 'en la puerta.': 'у двери.', 'Para preguntas, alianzas y mensajes que necesiten llegar a algún lado.': 'Для вопросов, союзов и сообщений, которые должны куда-то дойти.',
    'Nombre': 'Имя', '¿Cómo te llamás?': 'Как тебя зовут?', 'Correo': 'Почта', 'Mensaje': 'Сообщение', 'Escribí sin pedir perdón.': 'Пиши без извинений.', 'Enviar mensaje →': 'Отправить сообщение →',
    'GUÍA DE LECTURA': 'РУКОВОДСТВО ПО ЧТЕНИЮ', 'Herramientas para': 'Инструменты для', 'recorrer el archivo.': 'изучения архива.', 'Atajos y opciones disponibles para leer sin apuro.': 'Команды и настройки для неспешного чтения.',
    'Abrí la búsqueda global.': 'Откройте глобальный поиск.', 'Cambiá de nota cuando una está abierta.': 'Переключайтесь между открытыми заметками.', 'Cerrá búsquedas, notas e imágenes ampliadas.': 'Закрывайте поиск, заметки и увеличенные изображения.', 'Acercá o alej á las imágenes ampliadas.': 'Увеличивайте или уменьшайте изображения.',
    'Elegí idioma, color, tamaño de texto, tipografía y contraste. Tus elecciones se guardan en este navegador.': 'Выберите язык, цвет, размер текста, шрифт и контраст. Настройки сохраняются в браузере.',
    'ARCHIVO EN PREPARACIÓN': 'АРХИВ ГОТОВИТСЯ', 'Lo que viene': 'То, что впереди', 'también circula.': 'тоже циркулирует.',
    'Estamos preparando nuevas ediciones, lecturas, muestras y registros para sumar al archivo común.': 'Мы готовим новые выпуски, тексты, выставки и записи для общего архива.',
    'Mientras tanto, podés recorrer las publicaciones actuales, guardar notas y volver cuando la tinta se mueva otra vez.': 'А пока можно изучить текущие публикации, сохранить заметки и вернуться, когда краска снова придёт в движение.', 'IR AL ARCHIVO →': 'ПЕРЕЙТИ В АРХИВ →',
    'ERROR 404': 'ОШИБКА 404', 'Esta página': 'Эта страница', 'se fugó.': 'сбежала.', 'La imprenta sigue encendida, pero esta hoja no está en el archivo.': 'Печатный станок работает, но этого листа нет в архиве.', 'Volver a la portada': 'Вернуться к обложке',
    'Gato negro junto a una imprenta abandonada': 'Чёрный кот рядом с заброшенным печатным станком',
  },
};

function translateDeep<T>(value: T, locale: Exclude<Locale, 'es'>): T {
  if (typeof value === 'string') return (translations[locale][value] ?? value) as T;
  if (Array.isArray(value)) return value.map(item => translateDeep(item, locale)) as T;
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, translateDeep(item, locale)])) as T;
  return value;
}

export function createPublicContent(coverUrl: string, stateImageUrl: string, moderationEmailImageUrl = stateImageUrl) {
  const socialLinks = [
    { icon: 'spotify', label: 'Playlist en Spotify', url: 'https://open.spotify.com/' },
    { icon: 'youtube', label: 'Canal de YouTube', url: 'https://www.youtube.com/' },
    { icon: 'instagram', label: 'Instagram', url: 'https://www.instagram.com/' },
    { icon: 'facebook', label: 'Facebook', url: 'https://www.facebook.com/' },
    { icon: 'x', label: 'X', url: 'https://x.com/' },
  ];
  const es = {
    brand: { name: 'La Guillotina', publicationType: 'Revista anarquista', statement: 'Contra toda autoridad', headerLine: 'REVISTA ANARQUISTA / CONTRA TODA AUTORIDAD' },
    navigation: [
      { label: 'Inicio', to: '/', sortOrder: 0 }, { label: 'Ediciones', to: '/archivo', sortOrder: 1 }, { label: 'Quiénes somos', to: '/quienes-somos', sortOrder: 2 },
      { label: 'Manifiesto', to: '/manifiesto', sortOrder: 3 }, { label: 'Colaborar', to: '/colaborar', sortOrder: 4 }, { label: 'Contacto', to: '/contacto', sortOrder: 5 },
    ],
    footer: { statement: 'HECHA SIN AMO · SIN COPYRIGHT · COPIÁ · DIFUNDÍ · ORGANIZATE', socialPrompt: 'SEGUÍ LA SEÑAL', socialLinks },
    authentication: {
      triggerLabel: 'INGRESAR / SUMATE', eyebrow: 'ACCESO / COMUNIDAD', kicker: 'EL ARCHIVO SE CONSTRUYE ENTRE MUCHAS',
      privacyNote: 'No entregamos tus datos. La información circula con cuidado y las métricas son anónimas por defecto.',
      localNote: 'Tu sesión y tus preferencias se gestionan de forma segura para que puedas conservar lecturas, comentarios y guardadas.',
      login: { title: 'VOLVÉ A ENTRAR', copy: 'Ingresá para seguir conversaciones, guardar lecturas y participar.', submitLabel: 'INGRESAR' },
      register: { title: 'SUMATE A LA RED', copy: 'Creá tu acceso para dejar notas, seguir publicaciones y sostener este archivo común.', submitLabel: 'CREAR CUENTA' },
    },
    archive: {
      eyebrow: 'MEMORIA EN PAPEL', title: { main: 'Archivo de', accent: 'ediciones' }, intro: 'Una colección en construcción. Cada número es una conversación que no termina.',
      magazinesLabel: 'Revistas', booksLabel: 'Libros', showcaseLabel: 'Muestra', multimediaLabel: 'Multimedia',
      booksEmpty: 'Todavía no hay libros publicados. Próximamente encontrarás cuadernos, investigaciones y textos para descargar.',
    },
    pages: {
      about: { eyebrow: 'QUIÉNES SOMOS', title: { main: 'Una red de', accent: 'voces indóciles.' }, lead: 'La Guillotina nace de la necesidad de encontrarnos fuera de las instituciones que administran nuestras vidas.', paragraphs: ['Somos un colectivo abierto de personas que escriben, dibujan, investigan, traducen, fotografían y hacen cosas con sus manos. No hablamos por nadie: hacemos sitio para que hablen muchas.', 'Creemos en la autonomía, el apoyo mutuo, la imaginación y la alegría como prácticas políticas.'] },
      manifesto: {
        eyebrow: 'MANIFIESTO', title: { main: 'No hay libertad', accent: 'sin desobediencia.' },
        statements: ['No pedimos permiso para existir, pensar ni organizarnos.', 'Desconfiamos de todo poder que se pretenda necesario.', 'Practicamos el apoyo mutuo antes que la competencia.', 'Defendemos una cultura libre, situada y compartida.', 'Hacemos de la crítica una herramienta y del cuidado, una fuerza.'],
        items: [
          { id: 'freedom-as-practice', title: 'La libertad se practica', paragraphs: ['No esperamos autorización para pensar, crear o reunirnos. La autonomía empieza cuando reconocemos nuestra capacidad colectiva para decidir.', 'Desobedecer no es un gesto vacío: es abrir espacio para otras relaciones, asumir sus consecuencias y sostenerlas en común.'] },
          { id: 'power-is-not-inevitable', title: 'Ningún poder es inevitable', paragraphs: ['Toda autoridad que se presenta como natural oculta una historia, intereses y mecanismos concretos de obediencia.', 'Interrogar esas estructuras permite imaginar cómo desmontarlas sin reemplazar un mando por otro.'] },
          { id: 'mutual-aid-organizes', title: 'El apoyo mutuo organiza', paragraphs: ['Cooperar no es caridad ni una solución de emergencia: es una manera material de distribuir recursos, tiempo y conocimiento.', 'Las redes que construimos hoy ensayan formas de vida donde nadie queda aislado frente a una necesidad.'] },
          { id: 'culture-circulates', title: 'La cultura debe circular', paragraphs: ['Las ideas crecen cuando pueden copiarse, traducirse, discutirse y transformarse en contextos que sus autoras no controlan.', 'Defendemos una cultura situada que reconoce procedencias y cuidados sin convertir el conocimiento en propiedad cercada.'] },
          { id: 'care-is-struggle', title: 'Cuidar también es luchar', paragraphs: ['La crítica pierde fuerza si reproduce el agotamiento, el desprecio o las jerarquías que pretende cuestionar.', 'Hacer lugar para la escucha, el descanso y la alegría vuelve sostenible la rebeldía y amplía quiénes pueden participar.'] },
        ],
      },
      collaborate: { eyebrow: 'COLABORAR', title: { main: 'Mandá una chispa.', accent: 'Hagamos incendio.' }, lead: 'Buscamos textos, ilustraciones, fotos, poemas, crónicas, traducciones y afiches.', paragraph: 'No hace falta tener currículum ni hablar como un libro. Nos interesan las ideas que nacen de la experiencia y las preguntas que vale la pena sostener.', actionLabel: 'Escribir a la redacción', actionHref: 'mailto:colabora@laguillotina.fanzine', donation: { eyebrow: 'APOYO MUTUO', title: { main: 'Sostené el archivo.', accent: 'Hagamos incendio.' }, alias: 'LA.GUILLOTINA', label: 'DONAR POR MERCADO PAGO', url: 'https://link.mercadopago.com.ar/la-guillotina' } },
      contact: { eyebrow: 'CONTACTO', title: { main: 'Dejá una nota', accent: 'en la puerta.' }, lead: 'Para preguntas, alianzas y mensajes que necesiten llegar a algún lado.', form: { name: { label: 'Nombre', placeholder: '¿Cómo te llamás?' }, email: { label: 'Correo', placeholder: 'tu@correo.org' }, message: { label: 'Mensaje', placeholder: 'Escribí sin pedir perdón.' }, submitLabel: 'Enviar mensaje →' } },
      help: { eyebrow: 'GUÍA DE LECTURA', title: { main: 'Herramientas para', accent: 'recorrer el archivo.' }, lead: 'Atajos y opciones disponibles para leer sin apuro.', shortcuts: [{ keys: '/ · Ctrl/Cmd + K', label: 'Abrí la búsqueda global.' }, { keys: '← · →', label: 'Cambiá de nota cuando una está abierta.' }, { keys: 'Esc', label: 'Cerrá búsquedas, notas e imágenes ampliadas.' }, { keys: '+ · −', label: 'Acercá o alej á las imágenes ampliadas.' }, { keys: 'Preferencias de lectura', label: 'Elegí idioma, color, tamaño de texto, tipografía y contraste. Tus elecciones se guardan en este navegador.' }] },
      soon: { eyebrow: 'ARCHIVO EN PREPARACIÓN', title: { main: 'Lo que viene', accent: 'también circula.' }, paragraphs: ['Estamos preparando nuevas ediciones, lecturas, muestras y registros para sumar al archivo común.', 'Mientras tanto, podés recorrer las publicaciones actuales, guardar notas y volver cuando la tinta se mueva otra vez.'], actionLabel: 'IR AL ARCHIVO →', actionHref: '/archivo' },
      notFound: { eyebrow: 'ERROR 404', title: { main: 'Esta página', accent: 'se fugó.' }, copy: 'La imprenta sigue encendida, pero esta hoja no está en el archivo.', actionLabel: 'Volver a la portada', actionHref: '/' },
    },
    assets: {
      defaultCover: { url: coverUrl, alt: 'Portada grabada de La Guillotina' },
      notFound: { url: stateImageUrl, alt: 'Gato negro junto a una imprenta abandonada' },
      emptyArchive: { url: stateImageUrl, alt: '' }, loading: { url: stateImageUrl, alt: '' },
      moderationEmail: { url: moderationEmailImageUrl, alt: 'Mesa de imprenta comunitaria al final de la jornada' },
    },
  };
  return { es, en: translateDeep(es, 'en'), ru: translateDeep(es, 'ru') };
}

export function createPublicSeo(coverUrl: string) {
  const base = (locale: Locale) => ({
    siteName: locale === 'en' ? 'The Guillotine' : locale === 'ru' ? 'Гильотина' : 'La Guillotina', defaultTitle: locale === 'en' ? 'The Guillotine — Anarchist magazine' : locale === 'ru' ? 'Гильотина — Анархистский журнал' : 'La Guillotina — Revista anarquista',
    defaultDescription: locale === 'en' ? 'Issues, notes, images, and shared records against all authority.' : locale === 'ru' ? 'Выпуски, заметки, изображения и общий архив против всякой власти.' : 'Ediciones, notas, imágenes y registros comunes contra toda autoridad.',
    defaultImage: { url: coverUrl, alt: 'Portada de La Guillotina' }, locale,
    pages: {
      '/': { title: 'La Guillotina', description: locale === 'en' ? 'The latest issue and its notes.' : locale === 'ru' ? 'Последний выпуск и его заметки.' : 'La última edición y sus notas.' },
      '/archivo': { title: locale === 'en' ? 'Archive' : locale === 'ru' ? 'Архив' : 'Archivo', description: locale === 'en' ? 'Issues, books, showcases, and multimedia.' : locale === 'ru' ? 'Выпуски, книги, выставки и мультимедиа.' : 'Ediciones, libros, muestras y multimedia.' },
      '/quienes-somos': { title: locale === 'en' ? 'About us' : locale === 'ru' ? 'О нас' : 'Quiénes somos', description: locale === 'en' ? 'The collective behind La Guillotina.' : locale === 'ru' ? 'Коллектив La Guillotina.' : 'El colectivo detrás de La Guillotina.' },
      '/manifiesto': { title: locale === 'en' ? 'Manifesto' : locale === 'ru' ? 'Манифест' : 'Manifiesto', description: locale === 'en' ? 'Principles and shared practices.' : locale === 'ru' ? 'Принципы и общие практики.' : 'Principios y prácticas compartidas.' },
      '/colaborar': { title: locale === 'en' ? 'Contribute' : locale === 'ru' ? 'Участвовать' : 'Colaborar', description: locale === 'en' ? 'Send materials or support the archive.' : locale === 'ru' ? 'Присылайте материалы или поддержите архив.' : 'Mandá materiales o sostené el archivo.' },
      '/contacto': { title: locale === 'en' ? 'Contact' : locale === 'ru' ? 'Контакт' : 'Contacto', description: locale === 'en' ? 'Contact the editorial collective.' : locale === 'ru' ? 'Связаться с редакцией.' : 'Contactá a la redacción.' },
    },
  });
  return { es: base('es'), en: base('en'), ru: base('ru') };
}
