import 'dotenv/config';
import { z } from 'zod';

const booleanString = z.enum(['true', 'false']).transform(value => value === 'true');
const optionalString = z.string().trim().transform(value => value || undefined).optional();

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  HOST: z.string().default('0.0.0.0'),
  PORT: z.coerce.number().int().min(1).max(65_535).default(3001),
  API_PREFIX: z.string().startsWith('/').default('/laguillotina/api/v1'),
  APP_PUBLIC_URL: z.string().url().default('http://localhost:5173'),
  FRONTEND_ORIGINS: z.string().default('http://localhost:5173,http://127.0.0.1:5173'),
  DATABASE_URL: z.string().min(1),
  LOG_LEVEL: z.enum(['fatal', 'error', 'warn', 'info', 'debug', 'trace', 'silent']).default('info'),
  TRUST_PROXY: booleanString.default(false),
  COOKIE_SECRET: z.string().min(32),
  ANONYMOUS_HMAC_SECRET: z.string().min(32),
  ANALYTICS_HMAC_SECRET: z.string().min(32),
  SESSION_COOKIE_NAME: z.string().default('lg_session'),
  SESSION_TTL_DAYS: z.coerce.number().int().min(1).max(365).default(30),
  COOKIE_SECURE: booleanString.default(false),
  COOKIE_SAME_SITE: z.enum(['lax', 'strict', 'none']).default('lax'),
  COOKIE_DOMAIN: optionalString,
  PASSWORD_RESET_TTL_MINUTES: z.coerce.number().int().min(10).max(1_440).default(60),
  STORAGE_DRIVER: z.enum(['local', 's3']).default('local'),
  LOCAL_STORAGE_PATH: z.string().default('./storage'),
  PUBLIC_STORAGE_BASE_URL: z.string().url().default('http://localhost:3001/laguillotina/api/v1/media'),
  MAX_VIDEO_BYTES: z.coerce.number().int().positive().default(524_288_000),
  MAX_DEFAULT_FILE_BYTES: z.coerce.number().int().positive().default(104_857_600),
  MULTIPART_THRESHOLD_BYTES: z.coerce.number().int().positive().default(104_857_600),
  SIGNED_UPLOAD_TTL_SECONDS: z.coerce.number().int().min(60).max(86_400).default(900),
  S3_ENDPOINT: optionalString,
  S3_REGION: z.string().default('auto'),
  S3_BUCKET: optionalString,
  S3_ACCESS_KEY_ID: optionalString,
  S3_SECRET_ACCESS_KEY: optionalString,
  S3_PUBLIC_BASE_URL: optionalString,
  MAIL_MODE: z.enum(['development', 'smtp']).default('development'),
  DEV_MAILBOX_PATH: z.string().default('./.dev-mailbox'),
  MODERATION_EMAIL_IMAGE_URL: optionalString,
  SMTP_HOST: optionalString,
  SMTP_PORT: z.coerce.number().int().positive().default(587),
  SMTP_USER: optionalString,
  SMTP_PASSWORD: optionalString,
  SMTP_FROM: optionalString,
  OAUTH_GOOGLE_CLIENT_ID: optionalString,
  OAUTH_GOOGLE_CLIENT_SECRET: optionalString,
  OAUTH_GOOGLE_CALLBACK_URL: optionalString,
  OAUTH_X_CLIENT_ID: optionalString,
  OAUTH_X_CLIENT_SECRET: optionalString,
  OAUTH_X_CALLBACK_URL: optionalString,
  ANALYTICS_RAW_RETENTION_DAYS: z.coerce.number().int().min(1).max(365).default(30),
  CRON_SECRET: z.string().min(16),
});

export function loadConfig(source: NodeJS.ProcessEnv = process.env) {
  const value = envSchema.parse(source);
  return {
    nodeEnv: value.NODE_ENV,
    host: value.HOST,
    port: value.PORT,
    apiPrefix: value.API_PREFIX.replace(/\/$/, ''),
    appPublicUrl: value.APP_PUBLIC_URL.replace(/\/$/, ''),
    frontendOrigins: value.FRONTEND_ORIGINS.split(',').map(origin => origin.trim().replace(/\/$/, '')).filter(Boolean),
    databaseUrl: value.DATABASE_URL,
    logLevel: value.LOG_LEVEL,
    trustProxy: value.TRUST_PROXY,
    cookieSecret: value.COOKIE_SECRET,
    anonymousHmacSecret: value.ANONYMOUS_HMAC_SECRET,
    analyticsHmacSecret: value.ANALYTICS_HMAC_SECRET,
    sessionCookieName: value.SESSION_COOKIE_NAME,
    sessionTtlDays: value.SESSION_TTL_DAYS,
    cookieSecure: value.COOKIE_SECURE,
    cookieSameSite: value.COOKIE_SAME_SITE,
    cookieDomain: value.COOKIE_DOMAIN,
    passwordResetTtlMinutes: value.PASSWORD_RESET_TTL_MINUTES,
    storageDriver: value.STORAGE_DRIVER,
    localStoragePath: value.LOCAL_STORAGE_PATH,
    publicStorageBaseUrl: value.PUBLIC_STORAGE_BASE_URL.replace(/\/$/, ''),
    maxVideoBytes: value.MAX_VIDEO_BYTES,
    maxDefaultFileBytes: value.MAX_DEFAULT_FILE_BYTES,
    multipartThresholdBytes: value.MULTIPART_THRESHOLD_BYTES,
    signedUploadTtlSeconds: value.SIGNED_UPLOAD_TTL_SECONDS,
    s3: {
      endpoint: value.S3_ENDPOINT,
      region: value.S3_REGION,
      bucket: value.S3_BUCKET,
      accessKeyId: value.S3_ACCESS_KEY_ID,
      secretAccessKey: value.S3_SECRET_ACCESS_KEY,
      publicBaseUrl: value.S3_PUBLIC_BASE_URL?.replace(/\/$/, ''),
    },
    mail: {
      mode: value.MAIL_MODE,
      developmentMailboxPath: value.DEV_MAILBOX_PATH,
      moderationImageUrl: value.MODERATION_EMAIL_IMAGE_URL ?? `${value.PUBLIC_STORAGE_BASE_URL.replace(/\/$/, '')}/seed/comment-moderation-panorama.png`,
      smtpHost: value.SMTP_HOST,
      smtpPort: value.SMTP_PORT,
      smtpUser: value.SMTP_USER,
      smtpPassword: value.SMTP_PASSWORD,
      smtpFrom: value.SMTP_FROM,
    },
    oauth: {
      google: {
        clientId: value.OAUTH_GOOGLE_CLIENT_ID,
        clientSecret: value.OAUTH_GOOGLE_CLIENT_SECRET,
        callbackUrl: value.OAUTH_GOOGLE_CALLBACK_URL,
      },
      x: {
        clientId: value.OAUTH_X_CLIENT_ID,
        clientSecret: value.OAUTH_X_CLIENT_SECRET,
        callbackUrl: value.OAUTH_X_CALLBACK_URL,
      },
    },
    analyticsRawRetentionDays: value.ANALYTICS_RAW_RETENTION_DAYS,
    cronSecret: value.CRON_SECRET,
  } as const;
}

export type AppConfig = ReturnType<typeof loadConfig>;
